import type { WardRisk, LedgerData, AlertData } from "./types";

/**
 * Deterministic demo data for the Console.
 *
 * These values mirror the Python ML model's predictions for the 5 demo
 * wards (regenerated from GET /predict/all on the forecast-ingest
 * service). When the API gateway is running, the dashboard fetches live
 * data instead. This ensures the demo always works — and stays visually
 * identical — even without backend services running.
 */

export const DEMO_WARD_RISKS: WardRisk[] = [
  {
    ward_id: "KE-039-NYANDO",
    score: 96.7,
    band: "severe",
    probability: 0.967,
    feature_contributions: {
      precip_3day_sum: 11.58,
      precip_5day_sum: 12.19,
      precip_max_daily: 7.65,
      discharge_ratio: 14.41,
      discharge_trend: 8.9,
      rainfall_anomaly: 10.32,
      antecedent_moisture: 8.04,
      exposure_score: 8.92,
      vulnerability_score: 7.41,
      flood_plain_fraction: 7.29,
      historical_flood_frequency: 0.0,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "River discharge ratio contributes 14.4 points (value: 1.73)",
      "5-day precipitation forecast contributes 12.2 points (value: 380.00)",
      "3-day precipitation forecast contributes 11.6 points (value: 199.50)",
      "Rainfall anomaly vs. historical contributes 10.3 points (value: 6.76)",
      "Ward exposure (people/assets at risk) contributes 8.9 points (value: 0.72)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-21T09:00:00Z",
    inputs_hash: "8532360f40c9b465",
    source: "deterministic-demo-fixture",
    ward_name: "Nyando",
    river: "Nyando",
    population_at_risk: 48200,
    households_eligible: 9640,
    forecast_horizon_days: 4,
    latitude: -0.1725,
    longitude: 34.9192,
  },
  {
    ward_id: "KE-039-BUDALANGI",
    score: 53.3,
    band: "high",
    probability: 0.533,
    feature_contributions: {
      precip_3day_sum: 6.38,
      precip_5day_sum: 6.72,
      precip_max_daily: 4.21,
      discharge_ratio: 7.94,
      discharge_trend: 4.9,
      rainfall_anomaly: 5.69,
      antecedent_moisture: 4.43,
      exposure_score: 4.92,
      vulnerability_score: 4.08,
      flood_plain_fraction: 4.02,
      historical_flood_frequency: 0.0,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "River discharge ratio contributes 7.9 points (value: 0.81)",
      "5-day precipitation forecast contributes 6.7 points (value: 168.00)",
      "3-day precipitation forecast contributes 6.4 points (value: 88.20)",
      "Rainfall anomaly vs. historical contributes 5.7 points (value: 2.99)",
      "Ward exposure (people/assets at risk) contributes 4.9 points (value: 0.76)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-21T09:00:00Z",
    inputs_hash: "3cf31f0114fc32f5",
    source: "deterministic-demo-fixture",
    ward_name: "Budalangi",
    river: "Nzoia",
    population_at_risk: 31500,
    households_eligible: 6300,
    forecast_horizon_days: 4,
    latitude: 0.1208,
    longitude: 34.0833,
  },
  {
    ward_id: "KE-039-KANO",
    score: 44.7,
    band: "moderate",
    probability: 0.447,
    feature_contributions: {
      precip_3day_sum: 5.35,
      precip_5day_sum: 5.64,
      precip_max_daily: 3.53,
      discharge_ratio: 6.66,
      discharge_trend: 4.11,
      rainfall_anomaly: 4.77,
      antecedent_moisture: 3.71,
      exposure_score: 4.13,
      vulnerability_score: 3.43,
      flood_plain_fraction: 3.37,
      historical_flood_frequency: 0.0,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "River discharge ratio contributes 6.7 points (value: 0.95)",
      "5-day precipitation forecast contributes 5.6 points (value: 160.00)",
      "3-day precipitation forecast contributes 5.3 points (value: 84.00)",
      "Rainfall anomaly vs. historical contributes 4.8 points (value: 2.84)",
      "Ward exposure (people/assets at risk) contributes 4.1 points (value: 0.65)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-21T09:00:00Z",
    inputs_hash: "9adcfb41c05303d5",
    source: "deterministic-demo-fixture",
    ward_name: "Kano Plains",
    river: "Nyando",
    population_at_risk: 22800,
    households_eligible: 4560,
    forecast_horizon_days: 4,
    latitude: -0.1,
    longitude: 34.85,
  },
  {
    ward_id: "KE-039-RACHUONYO",
    score: 2.1,
    band: "low",
    probability: 0.021,
    feature_contributions: {
      precip_3day_sum: 0.25,
      precip_5day_sum: 0.26,
      precip_max_daily: 0.17,
      discharge_ratio: 0.31,
      discharge_trend: 0.19,
      rainfall_anomaly: 0.22,
      antecedent_moisture: 0.17,
      exposure_score: 0.19,
      vulnerability_score: 0.16,
      flood_plain_fraction: 0.16,
      historical_flood_frequency: 0.0,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "River discharge ratio contributes 0.3 points (value: 0.50)",
      "5-day precipitation forecast contributes 0.3 points (value: 44.00)",
      "3-day precipitation forecast contributes 0.2 points (value: 23.10)",
      "Rainfall anomaly vs. historical contributes 0.2 points (value: 0.78)",
      "Discharge trend contributes 0.2 points (value: 3.72)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-21T09:00:00Z",
    inputs_hash: "6b87c1be08e09c17",
    source: "deterministic-demo-fixture",
    ward_name: "Rachuonyo",
    river: "Awach",
    population_at_risk: 5400,
    households_eligible: 1080,
    forecast_horizon_days: 4,
    latitude: -0.3833,
    longitude: 34.75,
  },
  {
    ward_id: "KE-039-NZOIA",
    score: 95.8,
    band: "severe",
    probability: 0.958,
    feature_contributions: {
      precip_3day_sum: 11.47,
      precip_5day_sum: 12.08,
      precip_max_daily: 7.58,
      discharge_ratio: 14.28,
      discharge_trend: 8.82,
      rainfall_anomaly: 10.22,
      antecedent_moisture: 7.96,
      exposure_score: 8.84,
      vulnerability_score: 7.34,
      flood_plain_fraction: 7.22,
      historical_flood_frequency: 0.0,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "River discharge ratio contributes 14.3 points (value: 1.32)",
      "5-day precipitation forecast contributes 12.1 points (value: 312.00)",
      "3-day precipitation forecast contributes 11.5 points (value: 163.80)",
      "Rainfall anomaly vs. historical contributes 10.2 points (value: 5.55)",
      "Ward exposure (people/assets at risk) contributes 8.8 points (value: 0.69)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-21T09:00:00Z",
    inputs_hash: "541593a265cad498",
    source: "deterministic-demo-fixture",
    ward_name: "Nzoia",
    river: "Nzoia",
    population_at_risk: 44100,
    households_eligible: 8820,
    forecast_horizon_days: 4,
    latitude: 0.0833,
    longitude: 34.0167,
  },
];

export const DEMO_LEDGER: LedgerData = {
  events: [
    {
      id: "demo-risk-scored",
      occurred_at: "2026-08-20T12:00:00Z",
      type: "risk-scored",
      payload_hash: "a3f2c1d8e5b74902",
      previous_hash: "",
      hash: "7f8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
      index: 0,
    },
    {
      id: "demo-trigger-decided",
      occurred_at: "2026-08-20T12:02:00Z",
      type: "trigger-decided",
      payload_hash: "c4d5e6f7a8b90123",
      previous_hash: "7f8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
      hash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
      index: 1,
    },
    {
      id: "demo-payout-requested",
      occurred_at: "2026-08-20T12:03:00Z",
      type: "payout-requested",
      payload_hash: "e8f9a0b1c2d34567",
      previous_hash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
      hash: "3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4",
      index: 2,
    },
  ],
  count: 3,
  chain_valid: true,
  verified_at: "2026-08-20T12:05:00Z",
};

export const DEMO_ALERTS: AlertData[] = [
  {
    identifier: "resili-DEMO-001",
    sender: "resili (decision-support — follow KMD/NDMA)",
    sent: "2026-08-20T12:00:00+03:00",
    status: "Test",
    severity: "Severe",
    event: "Elevated flood risk likelihood — Nyando ward",
    description:
      "Forecast-based decision support indicates severe flood risk likelihood for Nyando ward (score 97/100). 5-day precipitation forecast exceeds the historical 90th percentile and the river discharge ratio is 1.7x the long-term mean. This is a probabilistic estimate, not a certainty.",
    instruction:
      "Follow official directives from KMD, NDMA, and county government authorities.",
    area_desc: "Nyando Ward, Kisumu County (ward-level generalisation)",
    expires: "2026-08-25T12:00:00+03:00",
  },
  {
    identifier: "resili-DEMO-002",
    sender: "resili (decision-support — follow KMD/NDMA)",
    sent: "2026-08-20T12:00:00+03:00",
    status: "Test",
    severity: "Severe",
    event: "Elevated flood risk likelihood — Nzoia ward",
    description:
      "Forecast-based decision support indicates severe flood risk likelihood for Nzoia ward (score 96/100). The river discharge ratio is 1.3x the long-term mean and antecedent soil moisture is high. This is a probabilistic estimate, not a certainty.",
    instruction:
      "Follow official directives from KMD, NDMA, and county government authorities.",
    area_desc: "Nzoia Ward, Busia County (ward-level generalisation)",
    expires: "2026-08-25T12:00:00+03:00",
  },
];
