import type { WardRisk, LedgerData, AlertData } from "./types";

/**
 * Deterministic demo data for the Operations Console.
 *
 * These values match the Python ML model's predictions for the
 * 5 demo wards. When the API gateway is running, the dashboard
 * will fetch live data instead. This ensures the demo always works
 * even without backend services running.
 */

export const DEMO_WARD_RISKS: WardRisk[] = [
  {
    ward_id: "KE-039-NYANDO",
    score: 82.3,
    band: "severe",
    probability: 0.823,
    feature_contributions: {
      precip_3day_sum: 18.5,
      precip_5day_sum: 12.3,
      precip_max_daily: 8.1,
      discharge_ratio: 15.2,
      discharge_trend: 6.8,
      rainfall_anomaly: 5.4,
      antecedent_moisture: 4.2,
      exposure_score: 5.1,
      vulnerability_score: 4.3,
      flood_plain_fraction: 1.5,
      historical_flood_frequency: 0.9,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "3-day precipitation forecast contributes 18.5 points (value: 156.30)",
      "River discharge ratio contributes 15.2 points (value: 1.89)",
      "5-day precipitation forecast contributes 12.3 points (value: 245.80)",
      "Peak daily rainfall contributes 8.1 points (value: 88.00)",
      "Discharge trend contributes 6.8 points (value: 12.50)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-20T12:00:00Z",
    inputs_hash: "a3f2c1d8e5b74902",
    source: "deterministic-demo-fixture",
    latitude: -0.1725,
    longitude: 34.9192,
  },
  {
    ward_id: "KE-039-BUDALANGI",
    score: 88.7,
    band: "severe",
    probability: 0.887,
    feature_contributions: {
      precip_3day_sum: 20.1,
      precip_5day_sum: 14.5,
      precip_max_daily: 9.2,
      discharge_ratio: 17.8,
      discharge_trend: 8.5,
      rainfall_anomaly: 6.2,
      antecedent_moisture: 4.8,
      exposure_score: 3.9,
      vulnerability_score: 2.5,
      flood_plain_fraction: 0.8,
      historical_flood_frequency: 0.4,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "3-day precipitation forecast contributes 20.1 points (value: 178.20)",
      "River discharge ratio contributes 17.8 points (value: 2.15)",
      "5-day precipitation forecast contributes 14.5 points (value: 280.10)",
      "Peak daily rainfall contributes 9.2 points (value: 92.50)",
      "Discharge trend contributes 8.5 points (value: 18.30)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-20T12:00:00Z",
    inputs_hash: "b4e3d2f9c6a85013",
    source: "deterministic-demo-fixture",
    latitude: 0.1208,
    longitude: 34.0833,
  },
  {
    ward_id: "KE-039-KANO",
    score: 52.1,
    band: "high",
    probability: 0.521,
    feature_contributions: {
      precip_3day_sum: 11.2,
      precip_5day_sum: 7.8,
      precip_max_daily: 5.1,
      discharge_ratio: 8.5,
      discharge_trend: 4.2,
      rainfall_anomaly: 3.8,
      antecedent_moisture: 3.1,
      exposure_score: 4.2,
      vulnerability_score: 2.8,
      flood_plain_fraction: 0.9,
      historical_flood_frequency: 0.5,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "3-day precipitation forecast contributes 11.2 points (value: 95.00)",
      "River discharge ratio contributes 8.5 points (value: 1.25)",
      "5-day precipitation forecast contributes 7.8 points (value: 155.20)",
      "Peak daily rainfall contributes 5.1 points (value: 48.00)",
      "Ward exposure contributes 4.2 points (value: 0.63)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-20T12:00:00Z",
    inputs_hash: "c5f4e3a0d7b96124",
    source: "deterministic-demo-fixture",
    latitude: -0.1,
    longitude: 34.85,
  },
  {
    ward_id: "KE-039-RACHUONYO",
    score: 18.4,
    band: "low",
    probability: 0.184,
    feature_contributions: {
      precip_3day_sum: 3.2,
      precip_5day_sum: 2.1,
      precip_max_daily: 1.5,
      discharge_ratio: 2.8,
      discharge_trend: 1.2,
      rainfall_anomaly: 1.8,
      antecedent_moisture: 1.5,
      exposure_score: 2.1,
      vulnerability_score: 1.4,
      flood_plain_fraction: 0.5,
      historical_flood_frequency: 0.3,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "3-day precipitation forecast contributes 3.2 points (value: 42.50)",
      "River discharge ratio contributes 2.8 points (value: 0.65)",
      "5-day precipitation forecast contributes 2.1 points (value: 68.30)",
      "Ward exposure contributes 2.1 points (value: 0.38)",
      "Rainfall anomaly contributes 1.8 points (value: 0.75)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-20T12:00:00Z",
    inputs_hash: "d6a5f4b1e8c07235",
    source: "deterministic-demo-fixture",
    latitude: -0.3833,
    longitude: 34.75,
  },
  {
    ward_id: "KE-039-NZOIA",
    score: 79.5,
    band: "severe",
    probability: 0.795,
    feature_contributions: {
      precip_3day_sum: 17.8,
      precip_5day_sum: 11.9,
      precip_max_daily: 7.5,
      discharge_ratio: 14.5,
      discharge_trend: 7.2,
      rainfall_anomaly: 5.8,
      antecedent_moisture: 4.5,
      exposure_score: 5.2,
      vulnerability_score: 3.5,
      flood_plain_fraction: 1.1,
      historical_flood_frequency: 0.5,
    },
    model_version: "risk-ml-v0.1.0",
    explanation: [
      "3-day precipitation forecast contributes 17.8 points (value: 165.80)",
      "River discharge ratio contributes 14.5 points (value: 2.05)",
      "5-day precipitation forecast contributes 11.9 points (value: 260.50)",
      "Discharge trend contributes 7.2 points (value: 15.70)",
      "Peak daily rainfall contributes 7.5 points (value: 85.00)",
      "This score is a decision-support estimate based on forecast data, not a certainty. Follow directives from KMD, NDMA, and county authorities.",
    ],
    assessed_at: "2026-08-20T12:00:00Z",
    inputs_hash: "e7b6a5c2f9d18346",
    source: "deterministic-demo-fixture",
    latitude: 0.0833,
    longitude: 34.0167,
  },
];

export const DEMO_LEDGER: LedgerData = {
  events: [
    {
      id: "demo-risk-scored",
      occurred_at: "2026-08-20T12:00:00Z",
      type: "risk-scored",
      payload_hash: "a3f2c1d8e5b74902",
      previous_hash: "",
      hash: "7f8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
      index: 0,
    },
    {
      id: "demo-trigger-decided",
      occurred_at: "2026-08-20T12:02:00Z",
      type: "trigger-decided",
      payload_hash: "c4d5e6f7a8b90123",
      previous_hash: "7f8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0",
      hash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
      index: 1,
    },
    {
      id: "demo-payout-requested",
      occurred_at: "2026-08-20T12:03:00Z",
      type: "payout-requested",
      payload_hash: "e8f9a0b1c2d34567",
      previous_hash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
      hash: "3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4",
      index: 2,
    },
  ],
  count: 3,
  chain_valid: true,
  verified_at: "2026-08-20T12:05:00Z",
};

export const DEMO_ALERTS: AlertData[] = [
  {
    identifier: "resili-DEMO-001",
    sender: "resili (decision-support — follow KMD/NDMA)",
    sent: "2026-08-20T12:00:00+03:00",
    status: "Test",
    severity: "Severe",
    event: "Elevated flood risk likelihood — Nyando ward",
    description:
      "Forecast-based decision support indicates elevated flood risk likelihood for Nyando ward. 3-day precipitation forecast exceeds historical 90th percentile. River discharge ratio is 1.9x long-term mean. This is a probabilistic estimate, not a certainty.",
    instruction:
      "Follow official directives from KMD, NDMA, and county government authorities.",
    area_desc: "Nyando Ward, Kisumu County (ward-level generalisation)",
    expires: "2026-08-25T12:00:00+03:00",
  },
  {
    identifier: "resili-DEMO-002",
    sender: "resili (decision-support — follow KMD/NDMA)",
    sent: "2026-08-20T12:00:00+03:00",
    status: "Test",
    severity: "Severe",
    event: "Elevated flood risk likelihood — Budalangi ward",
    description:
      "Forecast-based decision support indicates elevated flood risk likelihood for Budalangi ward. River discharge ratio is 2.15x long-term mean. Antecedent soil moisture is high (0.85).",
    instruction:
      "Follow official directives from KMD, NDMA, and county government authorities.",
    area_desc: "Budalangi Ward, Busia County (ward-level generalisation)",
    expires: "2026-08-25T12:00:00+03:00",
  },
];
